# Generated by Django 3.2.20 on 2023-10-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
